[package]
name = "s9_websocket"
version = "0.0.1"
edition = "2021"
authors = ["Alexander Silvennoinen <alex@silvennoinen.de>"]

[dependencies]
tungstenite = { version = "0.27", features = ["__rustls-tls"] }
tracing = "0.1"

[lib]
name = "s9_websocket"
path = "src/lib.rs"
